CREATE TABLE watchlist (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           player_name VARCHAR(255) NOT NULL,
                           user_id INTEGER NOT NULL,
                           last_stats_fetch TIMESTAMP,
                           added_at TIMESTAMP,
                           PRIMARY KEY (id)
);